# Test Our Algorithm 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

#  Train_test_split 

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 96, 140,  22, 141,  45,  56,  62, 120, 124,   3,  91,  35,  88,
       106, 134,  17, 147, 123, 125, 127, 103,  89,  38, 114,   7,  55,
        94, 119,  14,  47,  16, 116,  72, 115,   1,  84, 142,  44,  69,
       112,  59,  79,   0,  92, 132,  90,  82,  29,  32, 139, 118,  15,
        63, 130,  43, 144, 138, 128,  60, 126,  46,  49, 107,  36, 136,
        30, 111,  19,  95, 109,  58,  39, 100,  66, 122,   9,  80,  50,
        26,  71, 101, 148,  11,  54,  85,  53,  13,  42,  18, 146,  41,
        93,  21,  86, 135,  37,  33, 129,  67,  97,  87, 105,  99,  61,
         2,   4, 110,  70,   8,  27,   5,  20,  73,  51,  78,  68, 121,
        23, 149,  83,  98,  77,  52, 133,  81,  75, 117,  40,  10, 108,
        24,  76,  12,  48, 102,  57, 143, 113,   6,  64,  74,  34, 137,
        28,  31,  65, 104, 131, 145,  25])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


##  Using Algorithm of myself

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.KNN import KNNClassifier

In [19]:
my_knn_clf = KNNClassifier(k=3)

In [20]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [21]:
y_predict = my_knn_clf.predict(X_test)
print(y_predict)

[2 2 2 0 1 1 0 1 0 2 0 2 1 2 0 1 2 0 0 2 1 1 0 2 0 0 0 0 1 2]


In [22]:
y_test

array([2, 2, 2, 0, 2, 1, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 1,
       0, 2, 0, 0, 0, 0, 1, 1])

In [24]:
sum(y_predict == y_test)

28

In [26]:
sum(y_predict == y_test)/len(y_test)

0.9333333333333333

#  Train_test_split in sklearn

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
print(X_train.shape)
print(y_test.shape)

(120, 4)
(30,)


In [31]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
