# FancyIndex

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [6]:
ind = [3,5,8]

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],
                [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [12]:
X[0,col]

array([1, 2, 3])

In [13]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
col = [True,False,True,True]

In [15]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

# Compare of Numpy.array

In [25]:
%%timeit
s = np.arange(1000000)
np.sum(s)

2.65 ms ± 118 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%%timeit
sum = 0
for i in range(0,1000000):
    sum = sum + i

67.7 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [29]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [30]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [31]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [32]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [33]:
2 * x == 24 -4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [34]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
np.sum(x <= 3)

4

In [38]:
np.count_nonzero(x <= 3)

4

In [39]:
np.any(x == 0)

True

In [40]:
np.any(x < 0)

False

In [41]:
np.all(x >= 0)

True

In [42]:
np.all(x > 0)

False

In [43]:
np.sum(X % 2 == 0)

8

In [44]:
np.sum(X%2 == 0,axis=1)       # axis=0  row

array([2, 2, 2, 2])

In [45]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.sum(X%2 == 0,axis=0)       #axis=1 Colums

array([4, 0, 4, 0])

In [47]:
np.all(X>0,axis=1)

array([False,  True,  True,  True])

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
np.sum((x > 3) & ( x<10 ))

6

In [50]:
np.sum((x > 3) && ( x<10 ))

SyntaxError: invalid syntax (<ipython-input-50-c6329d3794a5>, line 1)

In [52]:
np.sum(~(x == 0))

15

In [53]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [54]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [55]:
X[X[:,3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])