# Jupyter Notebook Advanced Command

# %run

In [3]:
%run myscript/hello.py

Hello Machine Learning !


In [4]:
hello("imooc")

Hello imooc !


# %timeit

In [6]:
%timeit L = [i**2 for i in range(1000)]

301 µs ± 8.04 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit L = [i**2 for i in range(1000000)]

355 ms ± 4.72 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

383 µs ± 37.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### %time

In [19]:
%time L = [i**2 for i in range(1000)]

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 363 µs


In [22]:
%%time
L = []
for n in range(1000):
    L.append(n**2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 425 µs


In [23]:
import random
L = [random.random() for i in range(100000)]
%timeit L.sort()

3.65 ms ± 310 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.2'

In [3]:
import numpy as np

## The characteristic of Python List 

In [4]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L[5]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
import array

In [7]:
arr = array.array('i',[i for i in range(10)])

In [8]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5]

5

In [10]:
arr[5]=100

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [12]:
arr[5] = 'Machine Learning'

TypeError: an integer is required (got type str)

## numpy.array

In [13]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparr[5]

5

In [15]:
nparr.dtype

dtype('int64')

In [16]:
nparr[5] = 5.0

In [17]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr.dtype

dtype('int64')

In [21]:
nparr2 = np.array([1,2,3.0])

In [22]:
nparr2.dtype

dtype('float64')

## some else method of create numpy.array

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10).dtype

dtype('float64')

In [25]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [31]:
np.full(shape=(3,5),fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange

In [33]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
[i for i in range(0,1,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [42]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [44]:
np.linspace(0,20,11)  # third is mean how many numbers in form 0 to 20 

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [45]:
np.random.randint(0,10)

6

In [46]:
np.random.randint(0,10,10)

array([4, 1, 1, 6, 8, 1, 3, 0, 6, 2])

In [47]:
np.random.randint(4,8,size=10)

array([4, 4, 6, 5, 4, 7, 7, 6, 5, 7])

In [48]:
np.random.randint(4,8,size=(3,5))

array([[6, 4, 4, 4, 6],
       [7, 4, 6, 4, 7],
       [7, 4, 6, 4, 4]])

In [49]:
np.random.seed(666)     #After call the random seed ,they will be same

In [50]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [51]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [52]:
np.random.random()

0.2811684913927954

In [53]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [54]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [55]:
np.random.normal()

0.7760516793129695

In [68]:
np.random.normal(10,100)

49.63856739415942

In [69]:
np.random.normal(0,1,(3,5))

array([[ 0.57656584, -0.07019407,  0.91250436,  1.00470497,  0.41859929],
       [-1.52902454,  0.92487532,  0.18305429,  0.34543496, -0.8131543 ],
       [ 1.06325382,  0.25866385,  0.47285107,  1.0319698 , -0.16045655]])

In [70]:
np.random.normal?

In [80]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

# The basic operation of Numpy.array

In [86]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Basic property

In [88]:
x.ndim

1

In [89]:
X.ndim

2

In [90]:
x.shape

(10,)

In [91]:
X.shape

(3, 5)

In [92]:
x.size

10

In [93]:
X.size

15

###   The data visite of Numpy.array

In [95]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
x[0]

0

In [97]:
x[-1]

9

In [99]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
X[(0,0)]

0

In [101]:
X[2,2]

12

In [102]:
x[0:5]

array([0, 1, 2, 3, 4])

In [103]:
x[:5]

array([0, 1, 2, 3, 4])

In [104]:
x[5:]

array([5, 6, 7, 8, 9])

In [105]:
x[::2]

array([0, 2, 4, 6, 8])

In [106]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [107]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [109]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [111]:
X[0]

array([0, 1, 2, 3, 4])

In [112]:
X[0,:]

array([0, 1, 2, 3, 4])

In [113]:
X[:,0]

array([ 0,  5, 10])

In [114]:
X[:,0].ndim

1

In [115]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [116]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [117]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [120]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [123]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [124]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [125]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Reshape

In [126]:
x.shape

(10,)

In [127]:
x.ndim

1

In [128]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [132]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [136]:
B.ndim

2

In [137]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [138]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [139]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [140]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [141]:
x

array([1, 2, 3])

In [142]:
y

array([3, 2, 1])

In [143]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [144]:
z = np.array([666,666,666])

In [145]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [146]:
A = np.array([[1,2,3],
             [4,5,6]])

In [147]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [148]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [150]:
np.concatenate([z.reshape(1,-1),A])

array([[666, 666, 666],
       [  1,   2,   3],
       [  4,   5,   6]])

In [151]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
A2 = np.concatenate([A,z.reshape(1,-1)])

In [153]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [154]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [156]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [157]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [158]:
np.hstack([B,A])

array([[100, 100,   1,   2,   3],
       [100, 100,   4,   5,   6]])

## split

In [159]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
x1,x2,x3 = np.split(x,[3,7])

In [163]:
x1

array([0, 1, 2])

In [164]:
x2

array([3, 4, 5, 6])

In [165]:
x3

array([7, 8, 9])

In [166]:
np.split(x,[5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [167]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
A1,A2 = np.split(A,[2])

In [169]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [170]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
A1,A2 = np.split(A,[2],axis=1)

In [172]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [173]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [175]:
upper,lower = np.vsplit(A,[2])

In [176]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [177]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [178]:
left,right = np.hsplit(A,[2])

In [179]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [180]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [181]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [182]:
x,y = np.hsplit(data,[-1])

In [183]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [184]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [185]:
y[:,0]

array([ 3,  7, 11, 15])

# The calculate of Numpy.array

In [186]:
n = 10
L = [i for i in range(n)]

In [188]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [189]:
n =1000000
L = [i for i in range(n)]

In [190]:
%%time
A = []
for e in L:
    A.append(2*e)

CPU times: user 164 ms, sys: 20 ms, total: 184 ms
Wall time: 179 ms


In [191]:
%%time
A = [2*e for e in L]

CPU times: user 72 ms, sys: 28 ms, total: 100 ms
Wall time: 98.6 ms


In [193]:
import numpy as np
L = np.arange(n)

In [196]:
%%time
A = np.array(2*e for e in L)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 40.5 µs


In [205]:
%%time
A = 2 * L

CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 3.16 ms


In [198]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [206]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Universal Functions

In [207]:
x = np.arange(1,16).reshape((3,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [208]:
x +1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [209]:
x-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [210]:
x*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [211]:
x/2       #chufa

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [212]:
x//2      #quzheng

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [213]:
x%2       #qiuyu

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [214]:
1/x

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [215]:
np.abs(x)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])