# The calculate of numpy.array

In [10]:
n = 10
L = [i for i in range(n)]

In [11]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
n = 1000000
L = [i for i in range(n)]

In [14]:
%%time
A = []
for e in L:
    A.append(2*e)

CPU times: user 216 ms, sys: 16 ms, total: 232 ms
Wall time: 233 ms


In [15]:
%%time
A = [2*e for e in L]

CPU times: user 108 ms, sys: 24 ms, total: 132 ms
Wall time: 133 ms


In [16]:
%%time
A = 2 * L

CPU times: user 52 ms, sys: 12 ms, total: 64 ms
Wall time: 62.9 ms


In [19]:
import numpy as np
L = np.arange(n)

In [25]:
%%time
A = np.array(2*e for e in L)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 54.4 µs


In [26]:
%%time
A = 2 * L

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 3.11 ms


In [27]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [28]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Universal Functions

In [29]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [31]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [33]:
X / 2         #division

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [34]:
X // 2        # Rounding

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [35]:
X ** 2        #Power 

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [36]:
X % 2         #qiuyu

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [37]:
1/X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [38]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [40]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [41]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [42]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [43]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [44]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [45]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [46]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

# calculate of matrix

In [47]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [48]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [49]:
A + B

array([[10, 11],
       [12, 13]])

In [50]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [51]:
A * B

array([[ 0, 10],
       [20, 30]])

In [52]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [53]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [54]:
A

array([[0, 1],
       [2, 3]])

In [55]:
A.T

array([[0, 2],
       [1, 3]])

## The calculate of matrix and vector

In [56]:
v = np.array([1,2])

In [57]:
A

array([[0, 1],
       [2, 3]])

In [58]:
v + A

array([[1, 3],
       [3, 5]])

In [61]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [62]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [63]:
v

array([1, 2])

In [64]:
A

array([[0, 1],
       [2, 3]])

In [65]:
v * A

array([[0, 2],
       [2, 6]])

In [66]:
v.dot(A)

array([4, 7])

In [67]:
A.dot(v)

array([2, 8])

##  Inverse matrix

In [68]:
A

array([[0, 1],
       [2, 3]])

In [69]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [70]:
invA = np.linalg.inv(A)

In [71]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [72]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [73]:
X = np.arange(16).reshape(2,8)

In [74]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [75]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [77]:
pinvX = np.linalg.pinv(X)

In [78]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [79]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

# polymerization operation

In [80]:
import numpy as np

L = np.random.random(100)

In [81]:
L

array([0.78040459, 0.10346251, 0.70103762, 0.25131112, 0.70646743,
       0.74651416, 0.39137514, 0.30778965, 0.7742968 , 0.7361804 ,
       0.23274845, 0.53256226, 0.97435383, 0.21318541, 0.42233378,
       0.10454927, 0.51324847, 0.76938215, 0.47304905, 0.68655584,
       0.33844838, 0.61014386, 0.55846363, 0.23040054, 0.48193039,
       0.26497879, 0.34845203, 0.77798151, 0.91416602, 0.51654908,
       0.73646751, 0.94723689, 0.28280944, 0.62378085, 0.65137086,
       0.36240052, 0.41857912, 0.14551621, 0.37367768, 0.99118853,
       0.55559215, 0.35238672, 0.71972452, 0.81263111, 0.0018139 ,
       0.65092834, 0.95127547, 0.08592948, 0.95210444, 0.98657705,
       0.7623449 , 0.22856034, 0.11430268, 0.32980195, 0.72730671,
       0.85833036, 0.67487672, 0.65446698, 0.40028924, 0.27580087,
       0.09797809, 0.51298913, 0.01486415, 0.60695136, 0.10607804,
       0.53427276, 0.00567995, 0.63011124, 0.31679064, 0.87456995,
       0.32873621, 0.37324905, 0.67952328, 0.80652466, 0.35884

In [82]:
sum(L)

52.54587331051747

In [83]:
np.sum(L)

52.54587331051747

In [87]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

93.5 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
769 µs ± 921 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [88]:
np.min(big_array)

1.573550270528301e-06

In [89]:
np.max(big_array)

0.9999993150037594

In [90]:
big_array.min()

1.573550270528301e-06

In [91]:
big_array.max()

0.9999993150037594

In [92]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
np.sum(X)

120

In [94]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [95]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [96]:
np.prod(X)

0

In [97]:
np.prod(X + 1)

20922789888000

In [98]:
np.mean(X)

7.5

In [99]:
np.median(X)

7.5

In [100]:
v = np.array([1,1,2,3,10])
np.mean(v)

3.4

In [101]:
np.median(v)

2.0

In [103]:
np.percentile(big_array,q=50)

0.4990524328314871

In [104]:
np.median(big_array)

0.4990524328314871

In [105]:
np.percentile(big_array,q=100)

0.9999993150037594

In [107]:
np.max(big_array)

0.9999993150037594

In [109]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

1.573550270528301e-06
0.2493513707004161
0.4990524328314871
0.7490924806025733
0.9999993150037594


In [110]:
np.var(big_array)       #variance 

0.08330633748157856

In [111]:
np.std(big_array)                #standard deviation

0.2886283726205353

In [112]:
x = np.random.normal(0,1,size=1000000)

In [122]:
np.mean(x)

-0.0008621897485917283

In [123]:
np.std(x)

0.9989644304480104

# Index

In [124]:
np.min(x)

-4.670904670519962

In [125]:
np.argmin(x)

522249

In [126]:
x[522249]

-4.670904670519962

In [127]:
np.argmax(x)

407746

In [128]:
x[407746]

5.407431567966378

In [129]:
np.max(x)

5.407431567966378

###  Sorting and Using Index

In [147]:
X = np.arange(16)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [148]:
np.random.shuffle(X)
X

array([ 1,  4,  9,  8,  2, 11,  0, 14, 13, 15,  6, 10,  5,  3,  7, 12])

In [149]:
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [150]:
X

array([ 1,  4,  9,  8,  2, 11,  0, 14, 13, 15,  6, 10,  5,  3,  7, 12])

In [151]:
X.sort()

In [152]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [153]:
x = np.random.randint(10,size=(4,4))
x

array([[1, 6, 9, 4],
       [3, 9, 1, 2],
       [6, 9, 8, 1],
       [8, 5, 1, 6]])

In [154]:
np.sort(x)

array([[1, 4, 6, 9],
       [1, 2, 3, 9],
       [1, 6, 8, 9],
       [1, 5, 6, 8]])

In [155]:
np.sort(x,axis=1)        #mei yi hang dou shi you xu de 

array([[1, 4, 6, 9],
       [1, 2, 3, 9],
       [1, 6, 8, 9],
       [1, 5, 6, 8]])

In [156]:
np.sort(x,axis=0)       #mei yi lie doushi youxu de 

array([[1, 5, 1, 1],
       [3, 6, 1, 2],
       [6, 9, 8, 4],
       [8, 9, 9, 6]])

In [157]:
x

array([[1, 6, 9, 4],
       [3, 9, 1, 2],
       [6, 9, 8, 1],
       [8, 5, 1, 6]])

In [158]:
np.random.shuffle(X)

In [159]:
X

array([ 3,  0,  7,  6, 10, 14, 11,  1,  2,  9, 12, 13,  5,  4, 15,  8])

In [162]:
np.argsort(X)

array([ 1,  7,  8,  0, 13, 12,  3,  2, 15,  9,  4,  6, 10, 11,  5, 14])

In [163]:
np.partition(X,3)

array([ 0,  1,  2,  3, 10, 14, 11,  6,  7,  9, 12, 13,  5,  4, 15,  8])

In [164]:
np.argpartition(X,3)

array([ 1,  7,  8,  0,  4,  5,  6,  3,  2,  9, 10, 11, 12, 13, 14, 15])

In [165]:
x

array([[1, 6, 9, 4],
       [3, 9, 1, 2],
       [6, 9, 8, 1],
       [8, 5, 1, 6]])

In [166]:
np.argsort(x,axis=1)

array([[0, 3, 1, 2],
       [2, 3, 0, 1],
       [3, 0, 2, 1],
       [2, 1, 3, 0]])

In [167]:
np.argpartition(x,2,axis=1)

array([[0, 3, 1, 2],
       [2, 3, 0, 1],
       [3, 0, 2, 1],
       [2, 1, 3, 0]])